using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql;
using TelegramAIBot.Telemetry;

namespace TelegramAIBot.DataBase;

class UserContextDB(DbContextOptions<UserContextDB> dbContextOptions) : DbContext(dbContextOptions)
{
    public DbSet<UserProfileDB> UserProfiles { get; private set; }
    public DbSet<TelemetryRecordDB> TelemetryRecords { get; private set; }


    public async Task EnsureSchemaAsync()
    {
        var connection = (NpgsqlConnection)Database.GetDbConnection();
        var shouldClose = connection.State != System.Data.ConnectionState.Open;
        if (shouldClose)
            await connection.OpenAsync();

        try
        {
            await using (var createTelemetry = new NpgsqlCommand("""
                CREATE TABLE IF NOT EXISTS public."TelemetryRecords" (
                    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" TEXT NOT NULL,
                    "CreatedUtc" TIMESTAMP WITH TIME ZONE NOT NULL,
                    "CompressedPayload" BYTEA NOT NULL,
                    "Summary" TEXT NOT NULL,
                    "SummaryEmbeddingJson" TEXT NULL
                )
                """, connection))
            {
                await createTelemetry.ExecuteNonQueryAsync();
            }

            await using (var createTelemetryIndex = new NpgsqlCommand("""
                CREATE INDEX IF NOT EXISTS "IX_TelemetryRecords_UserId_CreatedUtc"
                    ON public."TelemetryRecords" ("UserId", "CreatedUtc" DESC)
                """, connection))
            {
                await createTelemetryIndex.ExecuteNonQueryAsync();
            }

            await using (var createProfiles = new NpgsqlCommand("""
                CREATE TABLE IF NOT EXISTS public."UserProfiles" (
                    "UserId" INTEGER PRIMARY KEY,
                    "Language" TEXT NOT NULL
                )
                """, connection))
            {
                await createProfiles.ExecuteNonQueryAsync();
            }
        }
        finally
        {
            if (shouldClose)
                await connection.CloseAsync();
        }
    }
}
